#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-indexer
Version  : 0.3.1
Release  : 5
URL      : https://rubygems.org/downloads/indexer-0.3.1.gem
Source0  : https://rubygems.org/downloads/indexer-0.3.1.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-2-Clause
Requires: rubygem-indexer-bin
BuildRequires : ruby
BuildRequires : rubygem-ae
BuildRequires : rubygem-qed
BuildRequires : rubygem-rdoc

%description
# INDEXER
**Enable Your Project's Metadata**
[![Build Status](https://secure.travis-ci.org/rubyworks/indexer.png)](http://travis-ci.org/rubyworks/indexer)
[![Gem Version](https://badge.fury.io/rb/indexer.png)](http://badge.fury.io/rb/indexer)

%package bin
Summary: bin components for the rubygem-indexer package.
Group: Binaries

%description bin
bin components for the rubygem-indexer package.


%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n indexer-0.3.1
gem spec %{SOURCE0} -l --ruby > rubygem-indexer.gemspec

%build
gem build rubygem-indexer.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
indexer-0.3.1.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/indexer-0.3.1.gem
/usr/lib64/ruby/gems/2.3.0/gems/indexer-0.3.1/.index
/usr/lib64/ruby/gems/2.3.0/gems/indexer-0.3.1/.yardopts
/usr/lib64/ruby/gems/2.3.0/gems/indexer-0.3.1/HISTORY.md
/usr/lib64/ruby/gems/2.3.0/gems/indexer-0.3.1/README.md
/usr/lib64/ruby/gems/2.3.0/gems/indexer-0.3.1/bin/index
/usr/lib64/ruby/gems/2.3.0/gems/indexer-0.3.1/data/indexer/index.kwalify
/usr/lib64/ruby/gems/2.3.0/gems/indexer-0.3.1/data/indexer/index.yes
/usr/lib64/ruby/gems/2.3.0/gems/indexer-0.3.1/data/indexer/index.yesi
/usr/lib64/ruby/gems/2.3.0/gems/indexer-0.3.1/data/indexer/ruby.txt
/usr/lib64/ruby/gems/2.3.0/gems/indexer-0.3.1/data/indexer/yaml.txt
/usr/lib64/ruby/gems/2.3.0/gems/indexer-0.3.1/lib/indexer.rb
/usr/lib64/ruby/gems/2.3.0/gems/indexer-0.3.1/lib/indexer/attributes.rb
/usr/lib64/ruby/gems/2.3.0/gems/indexer-0.3.1/lib/indexer/command.rb
/usr/lib64/ruby/gems/2.3.0/gems/indexer-0.3.1/lib/indexer/components.rb
/usr/lib64/ruby/gems/2.3.0/gems/indexer-0.3.1/lib/indexer/components/author.rb
/usr/lib64/ruby/gems/2.3.0/gems/indexer-0.3.1/lib/indexer/components/conflict.rb
/usr/lib64/ruby/gems/2.3.0/gems/indexer-0.3.1/lib/indexer/components/copyright.rb
/usr/lib64/ruby/gems/2.3.0/gems/indexer-0.3.1/lib/indexer/components/dependency.rb
/usr/lib64/ruby/gems/2.3.0/gems/indexer-0.3.1/lib/indexer/components/engine.rb
/usr/lib64/ruby/gems/2.3.0/gems/indexer-0.3.1/lib/indexer/components/organization.rb
/usr/lib64/ruby/gems/2.3.0/gems/indexer-0.3.1/lib/indexer/components/repository.rb
/usr/lib64/ruby/gems/2.3.0/gems/indexer-0.3.1/lib/indexer/components/requirement.rb
/usr/lib64/ruby/gems/2.3.0/gems/indexer-0.3.1/lib/indexer/components/resource.rb
/usr/lib64/ruby/gems/2.3.0/gems/indexer-0.3.1/lib/indexer/conversion.rb
/usr/lib64/ruby/gems/2.3.0/gems/indexer-0.3.1/lib/indexer/conversion/gemfile.rb
/usr/lib64/ruby/gems/2.3.0/gems/indexer-0.3.1/lib/indexer/conversion/gemspec.rb
/usr/lib64/ruby/gems/2.3.0/gems/indexer-0.3.1/lib/indexer/conversion/gemspec_exporter.rb
/usr/lib64/ruby/gems/2.3.0/gems/indexer-0.3.1/lib/indexer/core_ext.rb
/usr/lib64/ruby/gems/2.3.0/gems/indexer-0.3.1/lib/indexer/core_ext/hash/rekey.rb
/usr/lib64/ruby/gems/2.3.0/gems/indexer-0.3.1/lib/indexer/core_ext/hash/to_h.rb
/usr/lib64/ruby/gems/2.3.0/gems/indexer-0.3.1/lib/indexer/core_ext/kernel/cli.rb
/usr/lib64/ruby/gems/2.3.0/gems/indexer-0.3.1/lib/indexer/error.rb
/usr/lib64/ruby/gems/2.3.0/gems/indexer-0.3.1/lib/indexer/gemfile.rb
/usr/lib64/ruby/gems/2.3.0/gems/indexer-0.3.1/lib/indexer/importer.rb
/usr/lib64/ruby/gems/2.3.0/gems/indexer-0.3.1/lib/indexer/importer/file.rb
/usr/lib64/ruby/gems/2.3.0/gems/indexer-0.3.1/lib/indexer/importer/gemfile.rb
/usr/lib64/ruby/gems/2.3.0/gems/indexer-0.3.1/lib/indexer/importer/gemspec.rb
/usr/lib64/ruby/gems/2.3.0/gems/indexer-0.3.1/lib/indexer/importer/ruby.rb
/usr/lib64/ruby/gems/2.3.0/gems/indexer-0.3.1/lib/indexer/importer/version.rb
/usr/lib64/ruby/gems/2.3.0/gems/indexer-0.3.1/lib/indexer/importer/yaml.rb
/usr/lib64/ruby/gems/2.3.0/gems/indexer-0.3.1/lib/indexer/loadable.rb
/usr/lib64/ruby/gems/2.3.0/gems/indexer-0.3.1/lib/indexer/metadata.rb
/usr/lib64/ruby/gems/2.3.0/gems/indexer-0.3.1/lib/indexer/model.rb
/usr/lib64/ruby/gems/2.3.0/gems/indexer-0.3.1/lib/indexer/revision.rb
/usr/lib64/ruby/gems/2.3.0/gems/indexer-0.3.1/lib/indexer/valid.rb
/usr/lib64/ruby/gems/2.3.0/gems/indexer-0.3.1/lib/indexer/validator.rb
/usr/lib64/ruby/gems/2.3.0/gems/indexer-0.3.1/lib/indexer/version/constraint.rb
/usr/lib64/ruby/gems/2.3.0/gems/indexer-0.3.1/lib/indexer/version/exceptions.rb
/usr/lib64/ruby/gems/2.3.0/gems/indexer-0.3.1/lib/indexer/version/number.rb
/usr/lib64/ruby/gems/2.3.0/specifications/indexer-0.3.1.gemspec

%files bin
%defattr(-,root,root,-)
/usr/bin/index
